# Generated by Django 2.2.6 on 2019-10-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='userId',
        ),
        migrations.AddField(
            model_name='member',
            name='IP',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='userid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.BinaryField(max_length=50),
        ),
    ]
