# Generated by Django 2.2.6 on 2019-10-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_auto_20191012_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.BinaryField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=24)),
            ],
        ),
    ]
