# Generated by Django 2.2.6 on 2019-10-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0003_prospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
