# Generated by Django 2.2.6 on 2019-10-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0004_auto_20191012_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
