# Generated by Django 2.2.6 on 2019-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0005_auto_20191013_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userid', models.IntegerField()),
                ('IP', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=256)),
                ('action', models.CharField(max_length=1)),
                ('keyid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('keysize', models.IntegerField()),
                ('mode', models.CharField(max_length=3)),
                ('keybytes', models.CharField(max_length=256)),
                ('ivbytes', models.CharField(max_length=256)),
            ],
        ),
    ]
