# Generated by Django 2.2.6 on 2019-10-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0006_history_keydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='keyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encrypt.KeyData'),
        ),
        migrations.AlterField(
            model_name='history',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encrypt.Member'),
        ),
    ]
