# Generated by Django 2.2.7 on 2019-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0008_auto_20191108_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
