# Generated by Django 2.2.7 on 2019-11-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0009_auto_20191108_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('IP', models.CharField(max_length=20)),
            ],
        ),
    ]
