# Generated by Django 2.2.7 on 2019-11-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0010_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='IP',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='IP',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='ivbytes',
            field=models.BinaryField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='keybytes',
            field=models.BinaryField(max_length=256),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='password',
            field=models.BinaryField(max_length=100),
        ),
    ]
