# Generated by Django 2.2.7 on 2019-11-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0011_auto_20191111_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='IP',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.BinaryField(max_length=100),
        ),
    ]
