# Generated by Django 2.2.7 on 2019-11-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0012_auto_20191111_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
